"use client";

type PrintProposalButtonProps = {
  title: string;
  content: string;
};

function escapeHtml(value: string) {
  return value
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export function PrintProposalButton({ title, content }: PrintProposalButtonProps) {
  function handlePrint() {
    const safeTitle = escapeHtml(title);
    const safeContent = escapeHtml(content).replaceAll("\n", "<br />");

    const printWindow = window.open("", "_blank", "width=900,height=1100");

    if (!printWindow) {
      alert("Please allow popups to print this proposal.");
      return;
    }

    printWindow.document.write(`
      <!doctype html>
      <html>
        <head>
          <title>${safeTitle}</title>
          <style>
            body {
              margin: 0;
              padding: 40px;
              font-family: Arial, sans-serif;
              color: #171717;
              background: #f6f2ea;
            }

            .page {
              max-width: 820px;
              margin: 0 auto;
              background: white;
              padding: 46px;
              border-radius: 22px;
              box-shadow: 0 25px 80px rgba(0,0,0,.12);
            }

            .brand {
              font-size: 13px;
              letter-spacing: .18em;
              text-transform: uppercase;
              color: #9c7a24;
              font-weight: 800;
              margin-bottom: 16px;
            }

            h1 {
              font-size: 34px;
              margin: 0 0 24px;
              color: #111827;
            }

            .content {
              font-size: 15px;
              line-height: 1.75;
            }

            .footer {
              margin-top: 40px;
              padding-top: 18px;
              border-top: 1px solid #e8dfcf;
              color: #777;
              font-size: 12px;
            }

            @media print {
              body {
                background: white;
                padding: 0;
              }

              .page {
                box-shadow: none;
                border-radius: 0;
              }
            }
          </style>
        </head>
        <body>
          <div class="page">
            <div class="brand">ClientPilot AI</div>
            <h1>${safeTitle}</h1>
            <div class="content">${safeContent}</div>
            <div class="footer">
              Generated by ClientPilot AI.
            </div>
          </div>
          <script>
            window.onload = function() {
              window.print();
            };
          </script>
        </body>
      </html>
    `);

    printWindow.document.close();
  }

  return (
    <button className="btn gold" type="button" onClick={handlePrint}>
      Print / Save PDF
    </button>
  );
}